### ISSUE TITLE
Call to a member function execute()

### ISSUE THREAD

**Issue by mityukov** [Surzhikov/TelegramSiteHelper#1]
Здраствуйте, все сделал как в статье написано, но при попытке отправить сообщение валится такая ошибка (в log файл): 
"Call to a member function execute() on a non-object in /var/www/juicy-massacre.ru/public_html/TelegramSiteHelper/getUpdates.php on line 30"

Note: `apt-get install php5-sqlite` на сервере делал :-)

**Comment by kbereza** [comment]
В файле `TelegramDBConnect.php` нужно прописать абсолютный путь до файла с БД

``` php
<?php 
function connectDB() {
    $dbName = dirname(__FILE__) . '/telegram.db';

    try {
        $db = new PDO("sqlite:" . $dbName);
        $db->setAttribute(PDO::ATTR_TIMEOUT, 55); // Таймаут ожидания блокировки на запись
        $db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC); //  Дефолтный фетч - как ассоциативный массив
        $db->exec('PRAGMA journal_mode=WAL;');
        return ($db);
    }
    catch(PDOException $e) {
        exit($e->getMessage());
    }
}
```

**Comment by mityukov** [comment]
Прописал прямой путь + разрешения на запись проверил. Все-равно не работает чат.. Мож нехватает чего-то в инструкциях?

В /var/log/apache2/error.log в этот раз следующее:
[Fri Aug 14 05:04:54.339570 2015] [:error] [pid 10258] [client ...] PHP Notice:  Undefined index: wsChatHash in .../TelegramSiteHelper/sendMessage.php on line 21, referer: .../TelegramSiteHelper/
[Fri Aug 14 05:04:54.339944 2015] [:error] [pid 10258] [client ...] PHP Fatal error:  Call to a member function execute() on a non-object in .../TelegramSiteHelper/sendMessage.php on line 30, referer: .../TelegramSiteHelper/

**Comment by kbereza** [comment]
я еще для верности в `sendMessages.php` и `getUpdates.php` пути прописал через `dirname(__FILE__)`
